//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarData
    {
        public int ID { get; set; }
        public string Brand { get; set; }
        public Nullable<double> VolumeOfSales { get; set; }
        public Nullable<int> Year { get; set; }
    }
}
